---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: scaffold
  releaseName: scaffold
  valuesFile: values.yaml
  repo: https://sigstore.github.io/helm-charts
  version: 0.6.14
resources:
  - ../../cluster-scope/base/core/namespaces/fulcio-system
  - ../../cluster-scope/base/core/namespaces/rekor-system
  - ../../cluster-scope/base/core/namespaces/tuf-system
  - ../../cluster-scope/base/core/namespaces/trillian-system
  - ../../cluster-scope/base/core/namespaces/ctlog-system
  - ../../cluster-scope/base/rbac.authorization.k8s.io/rolebindings/sigstore
