apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: "argocdUrl:"
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded'] and repo.FullNameByRepoURL(app.spec.source.repoURL) == 'nexodus-io/nexodus'
      description: Application syncing has succeeded
      send: [github-json]
  service.webhook.github: |
    url: https://api.github.com
    headers:
    - name: "Accept"
      value: "application/vnd.github+json"
    - name: "Authorization"
      value: "token $argocd-token"
  template.github-json: |
    webhook:
      github: 
        method: POST
        path: /{{call .repo.FullNameByRepoURL .app.spec.source.repoURL}}/dispatches
        body: |
          {
            "ARGOCD_APP_NAME": "{{.app.metadata.name}}",
            "ARGOCD_SYNC_STATUS": "{{.app.status.sync.status}}",
            "ARGOCD_APP_BRANCH": "{{.app.spec.source.targetRevision}}",
            "ARGOCD_SYNC_REVISION": "{{.app.status.sync.revision}}",
            "ARGOCD_GIT_URL": "{{.app.spec.source.repoURL}}"
          }
