apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: argocd-notifications-secret
  dataFrom:
    - extract:
        key: rosa/openshift-gitops/argocd-notifications-secret
