apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - argocd-notifications-secret.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-notifications-cm
    patch: |
      - op: add
        path: /data/context
        value: "argocdUrl: http://openshift-gitops-server-openshift-gitops.apps.open-svc-sts.k1wl.p1.openshiftapps.com/"
