apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexodus-monitoring
spec:
  destination:
    name: in-cluster
    namespace: nexodus-monitoring
  source:
    path: deploy/nexodus-monitoring/overlays/rosa
    repoURL: "https://github.com/nexodus-io/nexodus"
    targetRevision: HEAD
  project: nexodus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
