apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:any-uid
  namespace: tekton-chains
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:any-uid
subjects:
- kind: ServiceAccount
  name: pipelines-scc
  namespace: tekton-chains
- kind: ServiceAccount
  name: tekton-chains-controller
  namespace: tekton-chains
