apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    name: in-cluster
    namespace: external-secrets-operator
  project: cluster-management
  source:
    path: external-secrets/overlays/rosa
    repoURL: https://github.com/redhat-et/rosa-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
