apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/core/namespaces/external-secrets-operator
  - ../../base/operators.coreos.com/subscriptions/external-secrets-operator
