apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../../../components/project-admin-rolebindings/rhde-validated-pattern
namespace: rhde-validated-pattern-staging
components:
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/x-large
