apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
resources:
  - ../../base
  - configmaps
  # Sealed secrets is currently removed because we have no dex clients at the moment.
  # - sealed-secrets/dex-clients-sealed.yaml
patchesStrategicMerge:
  - externalsecrets/dex-clients_patch.yaml